stages:
  - test
  - build

default:
  image: python:3.14

before_script:
  - python --version
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt

ruff:
  stage: test
  script:
    - ruff check .

pytest:
  stage: test
  script:
    - pytest -q

docker:
  stage: build
  image: docker:29.0.1-cli
  services:
    - name: docker:29.0.1-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker version
  script:
    - docker build -t customer-churn-api:ci .
